name: Manual workflow


on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn
          
      - name: Setup VPN config
        run: echo "${{ secrets.OVPN }}" > config.ovpn
        
      - name: Connect VPN
        run: sudo openvpn --config "./config.ovpn" --log "vpn.log" --daemon

      - name: Wait for a VPN connection
        timeout-minutes: 0.5
        run: until ping -c1 ${{ secrets.SERVER_IP }}; do sleep 5; done
      
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_LOGIN }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
            ls -al
