name: Deploy Main


on:
  push:
    branches:
      - new_tts


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn
          
      - name: Setup VPN config
        run: echo "${{ secrets.OVPN }}" > config.ovpn
        
      - name: Connect VPN
        run: sudo openvpn --config "./config.ovpn" --log "vpn.log" --daemon

      - name: Wait for a VPN connection
        timeout-minutes: 0.5
        run: until ping -c1 ${{ secrets.SERVER_IP }}; do sleep 5; done
      
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_LOGIN }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd ./docker
            mkdir test_english_bot
            cd ./test_english_bot
            git clone https://github.com/InGev007/english_bot.git
            git checkout new_tts
            cp ~/docker/english_bot/db/ ~/docker/test_english_bot/english_bot/ -r
            export TOKEN_TEST=${{ secrets.TG_TOKEN_TEST }}
            docker-compose build
            docker-compose up -d
